<a href="https://colab.research.google.com/github/vedanth-aggarwal/tensorflow_fundamentals_exploration/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR FUNDAMENTALS

* Introduction
* Getting info from tensors
* Manipulation of tensor
* Tensor and numpy
* @tf.function to speed up python func
* Using GPUs

In [ ]:
# Intro to Tensors
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7) # ctrl, shift space
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Dimensions
scalar.ndim

0

In [ ]:
# Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Dimensions
vector.ndim

1

In [ ]:
# Matrix
matrix = tf.constant([[10,7],[10,7]])
matrix.ndim

2

In [ ]:
matrix2 = tf.constant([[10.,7.],[10.,7.],[10,7]],dtype=tf.float16)
# int32 is default ( 32 bit precision)
matrix2.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

# Definitions
* Scalar : single number
* Vector : a number with direction ( windspeed and direction)
* Matrox : 2 dimensional array of num
* Tensor : n dimensional num array ( n is any num, 0 dim is scalar, 1 dim is vector)

In [ ]:
#tf.Variabel
changeable = tf.Variable([10,7])
changeable[0].assign(7)
changeable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Random tensors
# Arbitrary size with random numbers
# Neural network starts with random weights
r1 = tf.random.Generator.from_seed(42) # rerpducibility
r1 = r1.normal(shape=(3,2))
r2 = tf.random.Generator.from_seed(42)
r2 = r2.normal(shape=(3,2))
r1==r2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
# Shuffle elements
# If dataset is ordered, then neural network may learn the 1st item only Ramen then spageti
notshuffle = tf.constant([[10,7],[3,4],[2,5]])

# For shuffling in same order global and operation level seed should be same
tf.random.set_seed(42)
tf.random.shuffle(notshuffle,seed=42) # Not work alone

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Tensor from numpy array
tf.ones([10,7])
tf.zeros([10,7])

""" Tensors can be run on a GPU much faster for numerica computing than ndarrays"""

' Tensors can be run on a GPU much faster for numerica computing than ndarrays'

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)

# X = tf.constant(matrix) # capital for matrix / tensor
# y = tf.constant(vector) # small for vector

A = tf.constant(numpy_A,shape=(2,3,4)) # no. of elemnts must be same

In [ ]:
"""
Getting information from tensors
- Shape : element arrangement
- Rank : no of dimensions
- Axis/dimension
- Size
"""



'\nGetting information from tensors\n- Shape : element arrangement\n- Rank : no of dimensions\n- Axis/dimension\n- Size\n'

In [ ]:
rank4 = tf.zeros(shape=(2,3,4,5))
rank4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4[0]
rank4.shape,rank4.ndim,tf.size(rank4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# .dtype
# .ndim
# .shape
#Element along 0 axis  / last axis
rank4.shape[-1]
tf.size(rank4).numpy() # converts to normal

120

In [ ]:
# Indexing - Like Python Lists
rank4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank4[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank2 = tf.constant([[10,7],[1,7]])

In [ ]:
# Add extra dimension

rank3 = rank2[...,tf.newaxis] # None in numpy - ... = : :

In [ ]:
# Alternative
tf.expand_dims(rank2,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 7]]], dtype=int32)>

In [ ]:
# Manipulation
# Basic Airthmetic
t = tf.constant([[10,7],[3,4]])
t+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Built in functions
tf.multiply(t,10) # faster on GPU

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Matrix multiplication
# Dot vs element wise
tf.matmul(t,t)
t * t # element wise
t @ t # python dot product matrixmultiplication.xyz

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Dot product - tf.matmul() or tf.tensordot()
# transpose and reshape give diff outputs
# transpose flips axis - BETTER
# reshape just adjusts elemtent order to fit shape

In [ ]:
# Changing datatype of tensor

B = tf.constant([1.7,7.3])
C = tf.constant([7,10])
# float 32 to 16 bit mixed precision

In [ ]:
B = tf.cast(B,dtype=tf.float16)

In [ ]:
# AGGREGATION
# Condensing tensor from multiple values to smaller amount of values

# Get absolute values
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Get the minimum and maximum
tf.reduce_min(D)
# Get mean
tf.reduce_mean(D)
# Get sum
tf.reduce_sum(D)
# STD and variance

import tensorflow_probability as tfp
tfp.stats.variance(D)

tf.math.reduce_std(tf.cast(D,dtype=tf.float32))
tf.math.reduce_variance(tf.cast(D,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.25>

In [ ]:
# Positional max and min ( index of those values )
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=int64, numpy=42>

## Squeezing a tensor ( removing all single dimensions )

In [ ]:
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))

In [ ]:
squeeze = tf.squeeze(G)
squeeze # removes all dimensions of size 1

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [ ]:
# One hot encoding tensors - numerical encoding
# Machine Learning Mastery
"""
Red = 1,0,0
Blue = 0,1,0
Green = 0,0,1
"""

l = [0,1,2,3]
tf.one_hot(l,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(l,depth=3,on_value="YES",off_value='NO')

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'YES', b'NO', b'NO'],
       [b'NO', b'YES', b'NO'],
       [b'NO', b'NO', b'YES'],
       [b'NO', b'NO', b'NO']], dtype=object)>

In [ ]:
# MATHS
H = tf.range(1,10)
tf.square(H)
tf.sqrt(tf.cast(H,dtype=tf.float32))
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# Tensors & Numpy
J = tf.constant(np.array([3.0,3.5]))
np.array(J)
J.numpy()

array([3. , 3.5])

In [ ]:
numpy = tf.constant(np.array([3.0])) # float64
tens = tf.constant(np.array([3.0])) # float32

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices() # 'GPU'

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Apr 17 08:16:31 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# CUDA-enabled GPU is automatically used by Tensorflow when available